//Auth
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

//Bootcamps
export const GET__BOOTCAMPS = 'GET_BOOTCAMPS';
export const BOOTCAMPS_ERROR = 'BOOTCAMPS_ERROR';

// //users
// export const LOGIN_USER = 'LOGIN_USER';
export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
// export const RESET_PASSWORD = 'RESET_PASSWORD';
// export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

// export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
